### PR TITLE
Add option -DMUMPS_avx512vbmi (OFF by default)

### PR DESCRIPTION
**Pull request by gsylvand**
AVX512 VBMI instruction set is used in mumps BLR to speed-up adaptive precision feature. If ON, we test the support of avx512 vbmi at compilation, not at execution.

I only tested with gcc & linux. A more accurate test could be to try and compile mumps_flytes.c directly, but as it is it works with 5.9.1

### CODE REVIEW

**Comment by gsylvand** [comment]
I've added some documentation

**Comment by scivision** [comment]
Looking at the MUMPS 5.9.1 User manual and the GCC [docs](-mavx512f) and the MUMPS src/mumps_flytes.c it looks like GCC should have 

`-mavx512f -mavx512vbmi`

However, I experience errors like

> include/avx512vlbwintrin.h:94:1: error: inlining failed in call to ‘always_inline’ ‘_mm256_mask_storeu_epi8’: target specific option mismatch
   94 | _mm256_mask_storeu_epi8 (void *__P, __mmask32 __U, __m256i __A)
   
 As gsylvand does in this PR, using `-mavx512vl -mavx512vbmi` works

**Comment by scivision** [comment]
This was incorporated in the latest commit with edits, credited to gsyland
